# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a2a18839fd930c0637edf367ca1ecda9d061ba6db1125e62b06b57f53f6e37823e1252d6bf907dee86b21e1420187b6aeadf673943a5eda16e2301d7c8d4410

test:
  secret_key_base: 1b515d1af336cba98e4bfaa68d2f0df7a337d94d2121481b38fb5b6e47f38d7bd2896618e48b95e92ad673d3e569ad980a47fa2340f1dff9f26dbe94ea661626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
